version: '3.3'

services:
  mongo:
    container_name: "node-api-mongo-dev"
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: "node-api"
    volumes:
      - ./mongodb/init/:/docker-entrypoint-initdb.d
      - ./mongodb/docker-volume:/data/db
    ports:
      - "27017:27017"      
    networks:
      - app-network

networks:
  app-network: